version: '3'

services:
  web:
    build: 
      context: ./nuxt-client
      dockerfile: ./Dockerfile
    # command:  bash -c "make start_backend && make start front_end"
    container_name: frontend-nuxtJS
    ports:
      - "80:3000"
    depends_on:
      - api

  api:
    build: .      
    image: strapi/strapi
    container_name: backend-api-strapi

    # Mode Production only Mlab
    environment: 
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=testcluster0-nhxxh.mongodb.net

      # srv on port off
      - DATABASE_SRV=true
      # - DATABASE_PORT=27017 

      - DATABASE_NAME=server
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_SSL=true
      - DATABASE_AUTHENTICATION_DATABASE=admin
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
      
    # depends_on:
    #   - db
    restart: always

  # Mode development local
  # db:
  #   image: mongo
  #   container_name: mongo-DB
  #   # environment:
  #   #   - MONGO_INITDB_DATABASE=strapi
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./db:/data/db
  #   restart: always
